import "./globals.css";
import { Inter } from "next/font/google";
import Sidebar from "../sections/Sidebar";
import Header from "@/sections/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#F9F9F9]">
        <div className="flex flex-row">
          <Sidebar />
          <div className="bg-[#F9F9F9] w-full p-8">
            <Header />
            <div>{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
