import "./globals.css";
import { Inter } from "next/font/google";
import Sidebar from "../sections/Sidebar";
import Header from "@/sections/Header";
import { ThemeContextProvider } from "@/context/Store";
import LayoutChild from "./LayoutChild";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeContextProvider>
        <LayoutChild children={children} />
      </ThemeContextProvider>
    </html>
  );
}
